name: Continuous Deployment (CD)
 
on: 
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: SSH and deploy app
    # heroku deployment
    - uses: actions/checkout@v3
      run: |
        git config user.name "suwantosanjaya"
        git config user.email "suwantosanjaya@uin-suska.ac.id"
    - name: Deploy backend to Heroku
      run: git push heroku main:refs/heads/main --force
