name: Continuous Deployment (CD)
 
on: 
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: SSH and deploy app
      run: |
        git config user.name "suwantosanjaya"
        git config user.email "suwantosanjaya@uin-suska.ac.id"
        git fetch --all --unshallow
        git remote add heroku https://heroku:115f4d4a-4e10-496c-92a4-f8af7293068b@git.heroku.com/forum-api-v2.git
        printf "release: npx node-pg-migrate up\nweb: bin/start-nginx npm start" > Procfile
    - uses: actions/checkout@v3
    - name: Deploy backend to Heroku
      run: git push heroku master:refs/heads/master --force
